emotes:
  example:
    update-rate: "1s"
    frames:
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjhmZmYyMmM2ZTY1NDZkMGQ4ZWI3Zjk3NjMzOTg0MDdkZDJhYjgwZjc0ZmUzZDE2YjEwYTk4M2VjYWYzNDdlIn19fQ=="
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzY0MTY4MmY0MzYwNmM1YzlhZDI2YmM3ZWE4YTMwZWU0NzU0N2M5ZGZkM2M2Y2RhNDllMWMxYTI4MTZjZjBiYSJ9fX0="
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2UzYWNjNzhiNjI0YzA3MDg0OTE4NGUwYTI2NmQ5ZTk5YWE2NzFmYjNlMzhkNjZjMmMzYzUxOTExOTQ3OTMifX19"
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWZkZWY2OTI5ZWJhZjM5NGJjZTJlZTdlYTJhZGJiYjVjODNkN2NlMTdlM2I4NjE1YTkyOGFlZmFiZjg1YiJ9fX0="
  animals:
    update-rate: "3s"
    frames:
      - "NAME:Frcsty"
      - "UUID:asdasd"
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWUzZDUzNjIxYzhkYjQyNDQyZThkMjhlNmI0ZTg2OTg5MDRjODlkNjA2N2IyZjY0NDg2NTRlNDRlMDc0MDU5NiJ9fX0="
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWIyNmViMzVmOWQ4YWQxYzY4MmExMzdiY2FjODQzOWI5YzdmNTE0Mzk0OWY2NTBhN2NmNzU2ODQ4YjU4NmJkMyJ9fX0="
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzJjMmU3NTI1MGE4YzQ4YTRlNjZmYmY3OWVhNTBiNDQ2YjI0YTE3ZjlkOTlmY2I5NmVjOTQ0ZjkwMDYxOGIxZiJ9fX0="
      - "BASE:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzBkYmJiMzdlYTE0ZDc0ODkyZDYxMDU4NDcxNmEyZjI2ZGNjNjc3MDE5MGU0MGYzZjcxZjJmNTc4ZjYwOWJkYSJ9fX0="

cooldown: "1m"

settings:
  blacklisted-commands:
    - "/hat"

message:
  type: CHAT # ACTION_BAR, TITLE, SUBTITLE
  help-command: [
    "&9| &fEmotes",
    "&r",
    " &8* &7/emotes - Displays This Help Message",
    " &8* &7/emotes list - Lists All Configured Emotes",
    " &8* &7/emote <emote> [player] - Executes The Given Emote For Self Or Given User"
  ]
  list-command: [
    "&9| &7Created Emotes &8(&7{emotes_amount}&8): &f{emotes_list}"
  ]
  reload-command: [
    "&9| &7Successfully reloaded the plugin configuration and it's modules."
  ]
  invalid-emote: [
    "&9| &cInvalid emote!"
  ]
  invalid-target: [
    "&9| &cThat player doesn't exist or is not online"
  ]
  missing-permission: [
    "&9| &cYou do not have permission to use this emote!"
  ]
  blacklisted-commands-restriction: [
    "&9| &cYou may not use this command while using an emote."
  ]